python run_summarization.py \
    --model_name_or_path facebook/bart-base \
    --do_train \
    --do_eval \
    --train_file de.train.csv \
    --validation_file de.test.csv \
    --output_dir ./models/bart-base-spelling-de/ \
    --overwrite_output_dir \
    --per_device_train_batch_size=2 \
    --per_device_eval_batch_size=4 \
    --gradient_accumulation_steps=16 \
    --learning_rate="3e-4" \
    --num_train_epochs="2" \
    --predict_with_generate \
	--logging_steps="10" \
    --save_total_limit="2" \
    --max_target_length=1024 \
    --max_source_length=1024 \
    --save_strategy="steps" \
    --evaluation_strategy="steps" \
    --eval_steps="1000" \
    --save_steps="1000" \
    --metric_for_best_model="cer" \
    --greater_is_better="False" \
    --load_best_model_at_end \
    --fp16